# -*- coding: utf-8 -*-
"""clean_portfolio.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K7Adq0sPRntEQWTn9ptxD0nEVAGyvFN2
"""

def to_clean_portfolio(portfolio):
    
    '''
    data cleaning the portfolio dataframe
    
    INPUT:
    portfolio - the portfolio dataframe to be cleaned
    
    OUTPUT:
    portfolio - the cleaned portfolio dataframe
    
    '''
    clean_portfolio = portfolio.copy()
    
    # Change name of feature id to offer_id
    clean_portfolio = clean_portfolio.rename(columns={'id': 'offer_id'})

    # change the duration from day to hour
    clean_portfolio['duration'] = clean_portfolio['duration'] * 24
        
    # Break down the array in the 'channels' into separate columns
    channel_list = ['web', 'email', 'mobile', 'social']
    for item in channel_list:
        clean_portfolio[item] = clean_portfolio['channels'].apply(lambda x: 1 if item in x else 0)
        
    # Break down the array in the 'offer_type' into separate columns
    offer_list = ['bogo', 'informational', 'discount']
    
    for item in offer_list:
        clean_portfolio[item] = clean_portfolio['offer_type'].apply(lambda x: 1 if item in x else 0)
         
    # drop the 'channels'
    clean_portfolio = clean_portfolio.drop(['channels'], axis = 1)
    
    return clean_portfolio