# -*- coding: utf-8 -*-
"""clean_profile.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WePGoSkcS9RunD0qXPykssZ1OCyD3dHE
"""
import pandas as pd

def to_clean_profile(profile):
    
    """ Transforms a DataFrame that contains demographic data for each 
    customer
    
    INPUT:
        (Optional) data_dir: String that stores the full path to the
                             data directory
    
    OUTPUT:
        profile: DataFrame that contains demographic data for each 
                 customer
    """
    
    # copy dataframe from profile to clean_profile
    clean_profile = profile.copy()
    
    # Change name of culumn id to customer_id in profile dataframe
    clean_profile = clean_profile.rename(columns={'id': 'customer_id'})
    


    # Remove the rows with the age of 118
    clean_profile = clean_profile[clean_profile['age'] != 118]

    # Convert 'age' into 'age_bin'
    clean_profile['age_bin'] = pd.cut(clean_profile['age'], bins = range(10, 120, 10), right=False, 
                                            labels=['10s','20s', '30s', '40s', '50s', '60s', '70s', '80s', '90s', '100s'])

    # Convert 'income into 'income_bin' 
    clean_profile['income_bin'] = pd.cut(clean_profile['income'], bins = range(30000, 140000, 10000), right=False,\
                                         labels=['30k', '40k', '50k', '60k', '70k', '80k', '90k',\
                                                 '100k', '110k', '120k'])

    # Create feature 'became_member_year' in which customer became member from feature 'became_member_on'
    clean_profile['membership_since'] = pd.to_datetime(clean_profile['became_member_on'],format='%Y%m%d').dt.year

    clean_profile = clean_profile.drop(['age', 'became_member_on', 'income'], axis = 1)

    return clean_profile